debug: false

server:
  addr: "127.0.0.1:8080"
  host: "127.0.0.1"
  port: 8080

  readTimeout: 60
  writeTimeout: 60
  idleTimeout: 180

databases:
  default:
    host: "127.0.1"
    port: 3306
    user: "root"
    password: "123456"
    name: "mygo"
    maxOpenConns: 200
    maxIdleConns: 50
    connMaxLifetimeSecond: 600

redis:
  default: 
    addr: ""
    password: ""
    db: 0
    dial_timeout: 2
    read_timeout: 1
    write_timeout: 1
    pool_size: 20
    min_idle_conns: 100
    idle_timeout: 180

sentry:
  dsn: ""

hosts:
  login:
    addr: ""

cache:
  enable: true
